name: JVM CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 10
    - uses: actions/setup-node@v1
      with:
        node-version: 13.x
        registry-url: 'https://npm.pkg.github.com'
        scope: '@polypoly-eu'
    - name: npm install
      run: |
        npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
